namespace: servicenow
name: itsm
version: 2.0.0
readme: README.md
authors:
  - XLAB Steampunk <steampunk@xlab.si>
  - Abhijeet Kasurde <akasurde@redhat.com>
description: Ansible Collection for interacting with ServiceNow ITSM
license_file: LICENSE
tags:
  - servicenow
  - application
  - infrastructure
repository: https://github.com/ansible-collections/servicenow.itsm
homepage: https://github.com/ansible-collections/servicenow.itsm
issues: https://github.com/ansible-collections/servicenow.itsm/issues
build_ignore:
  - .gitignore
  - changelogs/.plugin-cache.yaml
