# SonarCloud project configuration for servicenow.itsm
# Complete documentation: https://docs.sonarqube.org/latest/analysis/analysis-parameters/

sonar.projectKey=ansible-collections_servicenow.itsm
sonar.organization=ansible-collections
sonar.sources=.
sonar.projectName=servicenow.itsm
sonar.python.coverage.reportPaths=coverage.xml

sonar.tests=tests/unit,tests/integration
sonar.python.version=3.12
sonar.newCode.referenceBranch=main

sonar.exclusions=tests/**,.tox/**


# rules to ignore
sonar.issue.ignore.multicriteria=e1,e2
# dont require literals when creating empty lists, or dicts
sonar.issue.ignore.multicriteria.e1.ruleKey=python:S7498
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.py

# dont require literals when creating empty sets
sonar.issue.ignore.multicriteria.e2.ruleKey=python:S7496
sonar.issue.ignore.multicriteria.e2.resourceKey=**/*.py
