---
name: changelog and linters

on:
  pull_request:

jobs:
  linters:
    name: Run custom linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Run linters
        run: CI=true make linters
